# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnivCounselingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('telno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='counselcenter',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
