# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccs', '0002_auto_20160909_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univcounselingcenter',
            name='address',
            field=models.CharField(max_length=200, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='univcounselingcenter',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='univcounselingcenter',
            name='manager',
            field=models.CharField(max_length=50, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='univcounselingcenter',
            name='telno',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='univcounselingcenter',
            name='title',
            field=models.CharField(max_length=100, verbose_name='센터명'),
        ),
    ]
